on:
  push:
    branches:
      - main

name: Sync to dots

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Sync Neovim
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SYNC_TOKEN }}
        with:
          source_file: "nvim/"
          destination_repo: "scottmckendry/dots"
          destination_folder: "/" 
          user_email: "39483124+scottmckendry@users.noreply.github.com"
          user_name: "Scott McKendry"
          commit_message: "${{ github.event.head_commit.message }} [skip ci]"
          git_server: "github.com"
